### ISSUE TITLE
Problems downloading the dataset

### ISSUE THREAD

**Issue by jesimonbarreto** [danielgordon10/vince#19]
Hi @danielgordon10,

You wrote in a past issue:

#Here is the full dataset as one large tar file. https://drive.google.com/open?id=1JGwb6ai1NugeW7KJDDE7G_bZ54D69teF

But the link doesn't work. Could you make that available again?

**Comment by danielgordon10** [comment]
I recently had to migrate the data off the UW servers. The dataset itself is several hundred GB, and I haven't found a cheap way to host it yet. What in particular do you want from the data? Would it be sufficient to have the metadata and you could download the videos yourself? Or could you use the YT8M dataset instead?

**Comment by danielgordon10** [comment]
You can use https://github.com/danielgordon10/vince/blob/master/datasets/info_files/r2v2_ids_train.txt to see the video URLs that I used. You can use Youtube-dl to download these videos and extract the frame ids also listed in that doc to recreate the R2V2 dataset. If you look in https://github.com/danielgordon10/vince/blob/master/datasets/video_cacher_dataset.py#L94 you can see some example code on how one would go about downloading a video and extracting the frames. Since I already list the frame IDs I used, the only post-processing you should need is `frames = video_utils.remove_border(frames)`

Maybe this weekend I will work on a script to help recreate the dataset from that file.

**Comment by danielgordon10** [comment]
YT8M is a dataset released by Google/Youtube of categorized video IDs. Essentially it gives a video and a category label. The dataset itself is wrapped in some tensorflow garbage, but I have another repo that exposes the classes and urls in python pickle format...that I also just realized has the same google drive issue as my Vince repo. I'll have to fix those links too. Luckily they are only a few 100 mb so I can host them myself. https://github.com/danielgordon10/youtube8m-data. Still if you can't wait for that, you can run https://github.com/danielgordon10/youtube8m-data/blob/master/parse_tfrecord.py which should recreate the YT8M dataset in python. On top of that I have a similar file to my r2v2_train.txt which has youtube urls and frame numbers using the yt8m dataset (but I omit the category label).

**Comment by danielgordon10** [comment]
See https://github.com/danielgordon10/vince#recreate-the-dataset on instructions to recreate the dataset.
